
package skillcourt5;

public class Menu extends javax.swing.JFrame
{
    int time;
    int numOfPads;
    boolean next = false;
    /**
     * Creates setup menu.
     */
    public Menu()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        gameTimeJL = new javax.swing.JLabel();
        tenSecJRB = new javax.swing.JRadioButton();
        thirtySecJRB = new javax.swing.JRadioButton();
        sixtySecJRB = new javax.swing.JRadioButton();
        numOfPadsJL = new javax.swing.JLabel();
        onePadJRB = new javax.swing.JRadioButton();
        twoPadJRB = new javax.swing.JRadioButton();
        threePadJRB = new javax.swing.JRadioButton();
        submitJB = new javax.swing.JButton();
        errorMsg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);

        gameTimeJL.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        gameTimeJL.setText("Please select a game duration:");

        buttonGroup2.add(tenSecJRB);
        tenSecJRB.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        tenSecJRB.setText("10 Sec");
        tenSecJRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenSecJRBActionPerformed(evt);
            }
        });

        buttonGroup2.add(thirtySecJRB);
        thirtySecJRB.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        thirtySecJRB.setText("30 Sec");
        thirtySecJRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thirtySecJRBActionPerformed(evt);
            }
        });

        buttonGroup2.add(sixtySecJRB);
        sixtySecJRB.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        sixtySecJRB.setText("60 Sec");
        sixtySecJRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixtySecJRBActionPerformed(evt);
            }
        });

        numOfPadsJL.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        numOfPadsJL.setText("Please select the number of pads:");

        buttonGroup1.add(onePadJRB);
        onePadJRB.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        onePadJRB.setText("1");
        onePadJRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onePadJRBActionPerformed(evt);
            }
        });

        buttonGroup1.add(twoPadJRB);
        twoPadJRB.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        twoPadJRB.setText("2");
        twoPadJRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoPadJRBActionPerformed(evt);
            }
        });

        buttonGroup1.add(threePadJRB);
        threePadJRB.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        threePadJRB.setText("3");
        threePadJRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threePadJRBActionPerformed(evt);
            }
        });

        submitJB.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        submitJB.setText("Submit");
        submitJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJBActionPerformed(evt);
            }
        });

        errorMsg.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(onePadJRB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(twoPadJRB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(threePadJRB))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gameTimeJL)
                            .addComponent(numOfPadsJL)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(tenSecJRB)
                        .addGap(18, 18, 18)
                        .addComponent(thirtySecJRB)
                        .addGap(18, 18, 18)
                        .addComponent(sixtySecJRB))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(submitJB, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 32, Short.MAX_VALUE)
                .addComponent(errorMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(numOfPadsJL)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(onePadJRB)
                    .addComponent(twoPadJRB)
                    .addComponent(threePadJRB))
                .addGap(46, 46, 46)
                .addComponent(gameTimeJL)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tenSecJRB)
                    .addComponent(thirtySecJRB)
                    .addComponent(sixtySecJRB))
                .addGap(37, 37, 37)
                .addComponent(submitJB, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(errorMsg)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tenSecJRBActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_tenSecJRBActionPerformed
    {//GEN-HEADEREND:event_tenSecJRBActionPerformed
       time = 10;
    }//GEN-LAST:event_tenSecJRBActionPerformed

    private void submitJBActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_submitJBActionPerformed
    {//GEN-HEADEREND:event_submitJBActionPerformed
        if(time == 0 || numOfPads == 0)
        {
            errorMsg.setForeground(new java.awt.Color(255, 0, 51));
            errorMsg.setText("ERROR: Must select number of pads AND game duration.");
        }
        else
        {
            next = true;
            dispose();
        }
    }//GEN-LAST:event_submitJBActionPerformed

    private void thirtySecJRBActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_thirtySecJRBActionPerformed
    {//GEN-HEADEREND:event_thirtySecJRBActionPerformed
        time = 30;
    }//GEN-LAST:event_thirtySecJRBActionPerformed

    private void onePadJRBActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_onePadJRBActionPerformed
    {//GEN-HEADEREND:event_onePadJRBActionPerformed
        numOfPads = 1;
    }//GEN-LAST:event_onePadJRBActionPerformed

    private void sixtySecJRBActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_sixtySecJRBActionPerformed
    {//GEN-HEADEREND:event_sixtySecJRBActionPerformed
        time = 60;
    }//GEN-LAST:event_sixtySecJRBActionPerformed

    private void twoPadJRBActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_twoPadJRBActionPerformed
    {//GEN-HEADEREND:event_twoPadJRBActionPerformed
        numOfPads = 2;
    }//GEN-LAST:event_twoPadJRBActionPerformed

    private void threePadJRBActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_threePadJRBActionPerformed
    {//GEN-HEADEREND:event_threePadJRBActionPerformed
        numOfPads = 3;
    }//GEN-LAST:event_threePadJRBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel errorMsg;
    private javax.swing.JLabel gameTimeJL;
    private javax.swing.JLabel numOfPadsJL;
    private javax.swing.JRadioButton onePadJRB;
    private javax.swing.JRadioButton sixtySecJRB;
    private javax.swing.JButton submitJB;
    private javax.swing.JRadioButton tenSecJRB;
    private javax.swing.JRadioButton thirtySecJRB;
    private javax.swing.JRadioButton threePadJRB;
    private javax.swing.JRadioButton twoPadJRB;
    // End of variables declaration//GEN-END:variables
}
